### ISSUE TITLE
Traceback:AttributeError

### ISSUE THREAD

**Issue by Aniket21mathur** [sugarlabs/devtutor-activity#5]
```
Traceback (most recent call last):
  File "/home/guest/GSOC/devtutor-activity/modules.py", line 182, in widgets
    self.add_line1()
  File "/home/guest/GSOC/devtutor-activity/modules.py", line 221, in add_line1
    title_entry1 = StopButton(self)
  File "/usr/lib/python2.7/dist-packages/sugar3/activity/widgets.py", line 89, in __init__
    activity.add_stop_button(self)
AttributeError: 'ShowModules' object has no attribute 'add_stop_button'
```

Reproducer:
1)Click on show modules.
2)And then Activity
3)And then clicking on Widgets results in the traceback.

**Comment by quozl** [comment]
Use three backticks to mark multiple lines.

**Comment by quozl** [comment]
Thanks.  I've had a moment to review the source code and history.  I don't think this issue is helpful.  Let's not raise an issue for each of the hundred things wrong with this experimental and unfinished activity?  :grimacing: 

See https://github.com/sugarlabs/devtutor-activity/issues/6 instead.

**Comment by Aniket21mathur** [comment]
I agree with you @quozl .Thanks for checking.
